---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.kube-system.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: kube-system
        path: "/mutatedns"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVSFZGRUZ5OXhaYkl6Z2NDY0hTOERMYXg2bWtVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXlNREV4TVRBeU1qTXlNRm9YRFRJeU1ESXhNREF5TWpNeU1Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTB6U1ZSelIzcXR3ekJ2M0JhRnoxV1l0eXptNFlrNGluaUJJcApCNXhzcTU4QXc4V3kwSzlLZjRhME01S2xEWlI5bmwvd3RLaHB0elhEdXRsVFdSaXdUcGpNcVVPTFYxSWxIVm90Cm1RN3F0dTVza1BGZ3diS2J0UEt6VzBLM2Mvb0N5N3RkU1BnQk1qZEQ3Z0h3NitTNUNzS2Q2cVJVV1hRdmVzOW0KNVZweS83WkxqMTZTdy91TjZDWkRseHJsamc2alNnbzVhNnV4ZnIxTVV2VGNHK1lOQitVQWN6ci84WEk2Mk1nNApPWnk1Nk8zOFlhaWRpVC9vNTRsMXB4a3RZWVVrZlVhSWhzaXlGMWI3a2hTRHZzU2s5Qmdsc2c0Kzd1UXQxWDJwCmtOYTdTdkMrREJhbU1EUjlKOEQ3QjIwUkJuN0o2TURRKzZ1Zy82bCtvRmhZYWdBbzF3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVK0ZhRytPSnoyWGJ1MmtuUjZSUGd6V2FqTXBZd0h3WURWUjBqQkJnd0ZvQVUrRmFHK09KegoyWGJ1MmtuUjZSUGd6V2FqTXBZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFCVTRpaTJJWCtEYjJSd001VlVLMHpqZmUvWDNZd00wRDB4elV3K0JzbTVwYWx2dzFtbHpZZUFrMktFNlQKOU9VMG1Zd3JKYUYzMEpzZ2JRRlV6ei9HRm1LL2d2NG1lMmFkdzdqYXV1SThBcG5ON21yby9RTk85cUdzZXhFVApxQnowSlc5aUJZOUwwdU1WTk1FRnhMWEdXaUs1ZVFIaC9qOUdtKzFEV2VHSEhFMEFmNXcyQWdGclc5RGtZRzVOCkxRT0JjVDhyMDhBY1VyaGJSRGw2YjNiWXUvTVh2a1hIcG9ieEkyZmJYbnp6UUhLM1d0QzhDcXNsSGZzem5qOFEKNmxXTm1CV3pUOTFxU3d3bXZ0eWw1dFNBd2RtUTFnSzZVWjJTSkpFZVU2Tmh6SXdqbEhrRWg1ZjFNVWlUUlZuNQpmT2c3MVB1OEZxYUY0cUx4NWhqeSs2STNlQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["admission.ke.com"]
        apiVersions: ["v1"]
        resources: ["dnsconfigs", "qoss"]
